# =============================================================================
# Forge — Inventory
# Prototype topology: 1 physical host + 2 KVM guests
#
# remote-workstation  → localhost (the physical box via 127.0.0.1)
# dev-workstation     → KVM guest  (SSH via 127.0.0.1:2222 after provisioning)
# forge-infra         → KVM guest  (SSH via 127.0.0.1:2223 after provisioning)
# =============================================================================

all:
  vars:    
    ansible_python_interpreter: /usr/bin/python3.13
    ansible_become_exe: /usr/bin/sudo.ws

  children:
    # ── Physical hosts ──────────────────────────────────────────────────────
    physical_hosts:
      hosts:
        remote-workstation:
          ansible_connection: local
          ansible_user: "{{ lookup('env','USER') }}" 

    # ── KVM guests (reachable only AFTER kvm role has provisioned them) ────
    vm_guests:
      vars: 
        ansible_user: forge                        # default non-root user inside VMs
        ansible_ssh_private_key_file: "{{ forge_ssh_key }}"
      hosts:
        dev-workstation:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        forge-infra:
          ansible_host: 127.0.0.1
          ansible_port: 2223
